//
// Generated file, do not edit! Created by nedtool 5.2 from serviceMsg.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __SERVICEMSG_M_H
#define __SERVICEMSG_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0502
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>serviceMsg.msg:16</tt> by nedtool.
 * <pre>
 * message senderMsg
 * {
 *     int source;
 * }
 * </pre>
 */
class senderMsg : public ::omnetpp::cMessage
{
  protected:
    int source;

  private:
    void copy(const senderMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const senderMsg&);

  public:
    senderMsg(const char *name=nullptr, short kind=0);
    senderMsg(const senderMsg& other);
    virtual ~senderMsg();
    senderMsg& operator=(const senderMsg& other);
    virtual senderMsg *dup() const override {return new senderMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const senderMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, senderMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __SERVICEMSG_M_H

